name: proyectos_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  syncfusion_flutter_pdfviewer: ^27.1.57
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  flutter_widget_from_html: ^0.17.1
  url_launcher: ^6.3.2
  table_calendar: ^3.1.3
  image_picker: ^1.2.1
  webview_flutter: ^4.13.1
  shared_preferences: ^2.5.4
  local_auth: ^3.0.1
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_unamis.png
    - assets/images/campus_virtual_banner.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_unamis.png"
